config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/insert', to: 'add_questions#new'
  post '/insert', to: 'add_questions#create'
  get '/paper', to: 'question_papers#new'
  post '/paper', to: 'question_papers#craete'
  get '/exam_paper', to: 'question_papers#exam_paper'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :add_questions
  resources :question_papers
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>

<p>
  This is the about page for Question Paper Generator System App.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>
<p>
  Get help on the Question Paper Generator System App here
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Question Paper Generator System</h1>
  <h2>This is the home page for the Question Paper Generator System App.</h2>

  <% if logged_in? %>
    <h3>Quick Links</h3>
    <div class="btn-group-vertical">
      <%= link_to "Insert Question", insert_path, class: "btn btn-primary" %>
      <%= link_to "All Questions", add_questions_path, class: "btn btn-primary" %>
      <%= link_to "Create Question Paper", paper_path, class: "btn btn-primary" %>
    </div>
  <% else %>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>
<%= link_to image_tag("ques.png", alt: "Question logo") %>