config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/insert', to: 'add_questions#new'
  post '/insert', to: 'add_questions#create'
  get '/paper', to: 'question_papers#new'
  post '/paper', to: 'question_papers#craete'
  get '/exam_paper', to: 'question_papers#exam_paper'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :add_questions
  resources :question_papers
end

app/models/question_paper.rb
class QuestionPaper < ApplicationRecord
  has_and_belongs_to_many :add_questions

  validates :name, presence: true, length: {maximum: 100}
  validates :fullmark, presence: true
  validates :module, presence: true, numericality: {only_integer: true, greater_than: 1, less_than: 6}
  validates :paper_difficulty, presence: true, inclusion: { in: %w(easy medium hard), message: "%{value} is not a valid difficulty"}
  validates :code, presence: true, allow_nil: true

  def current_paper
    @current_paper = QuestionPaper.last
  end
end

app/controllers/question_papers_controller.rb
class QuestionPapersController < ApplicationController

  def index

  end

  def show
    @question_paper = QuestionPaper.find(params[:id])

    @module = @question_paper.module
    @fullmark = @question_paper.fullmark
    @difficulty = @question_paper.paper_difficulty
    code = @question_paper.code

    if @fullmark==25
      if @difficulty=='easy'
        if @module==2
          @mod1_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 4)
          @mod1_ques2 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 3)
          @mod1_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 2)
          @mod1_ques4 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 1)

          @mod2_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 4)

          @mod2_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 3)

          @mod2_ques4_5 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 2)

        elsif @module==3
          @mod1_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 4)
          @mod1_ques2 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 3)
          @mod1_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 1)

          @mod2_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 3)

          @mod2_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 2)

          @mod3_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 4)
          @mod3_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 1)

        elsif @module==4
          @mod1_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 4)
          @mod1_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 2)

          @mod2_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 1)
          @mod2_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 3)

          @mod3_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 2)
          @mod3_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 1)

          @mod4_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 2)
          @mod4_ques2 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 3)
        elsif @module==5
          @mod1_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 2)
          @mod1_ques2 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 3)

          @mod2_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 1)
          @mod2_ques2_3 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 2)

          @mod3_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 4)
          @mod3_ques2 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 1)

          @mod4_ques1_2_3 = AddQuestion.limit(3).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 1)
          @mod4_ques4 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 2)

          @mod5_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 5)

        else
          flash[:danger] = "Module must be in between 2-5"
          redirect_to paper_path

        end

      elsif @difficulty=='medium'
        if @module==2
          @mod1_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 4)
          @mod1_ques2 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 3)
          @mod1_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 2)
          @mod1_ques4 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 1)

          @mod2_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 4)

          @mod2_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 3)

          @mod2_ques4_5 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 2)

        elsif @module==3
          @mod1_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 4)
          @mod1_ques2 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 3)
          @mod1_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 1)

          @mod2_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 3)

          @mod2_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 2)

          @mod3_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 4)
          @mod3_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 1)

        elsif @module==4
          @mod1_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 4)
          @mod1_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 2)

          @mod2_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 1)
          @mod2_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 3)

          @mod3_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 2)
          @mod3_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 1)

          @mod4_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 2)
          @mod4_ques2 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 3)

        elsif @module==5
          @mod1_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 2)
          @mod1_ques2 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 3)

          @mod2_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 1)
          @mod2_ques2_3 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 2)

          @mod3_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 4)
          @mod3_ques2 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 1)

          @mod4_ques1_2_3 = AddQuestion.limit(3).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 1)
          @mod4_ques4 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 2)

          @mod5_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 5)

        else
          flash[:danger] = "Module must be in between 2-5"
          redirect_to paper_path

        end

      elsif @difficulty=='hard'
        if @module==2
          @mod1_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 4)
          @mod1_ques2 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 3)
          @mod1_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 2)
          @mod1_ques4 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 1)

          @mod2_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 4)

          @mod2_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 3)

          @mod2_ques4_5 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 2)

        elsif @module==3
          @mod1_ques1 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 4)
          @mod1_ques2 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 3)
          @mod1_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'easy', course: code, mark: 1)

          @mod2_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 3)
          @mod2_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 2)

          @mod3_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 4)
          @mod3_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 1)

        elsif @module==4
          @mod1_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 4)
          @mod1_ques3 = AddQuestion.limit(1).order("RANDOM()").where(difficulty: 'medium', course: code, mark: 2)

          @mod2_ques1_2 = AddQuestion.limit(2).order("RANDOM()").where(difficulty: 'hard', course: code, mark: 1)

app/helpers/question_papers_helper.rb
module QuestionPapersHelper
end

app/views/question_papers/_form.html.erb
<%= form_for(@question_paper) do |f| %>
  <%= render 'shared/ques_paper_errors', object: @question_paper %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :code %>
  <%= f.text_field :code, class: 'form-control' %>

  <%= f.label :fullmark %>
  <%= f.select :fullmark, [25, 40], class: 'form-control' %>

  <%= f.label :paper_difficulty %>
  <%= f.select :paper_difficulty,['easy','medium','hard'], class: 'form-control' %>

  <%= f.label :module %>
  <%= f.number_field :module, class: 'form-control' %>


  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/question_papers/exam_paper.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>The choosen specification for the question paper are </h3>
    <section class="paper_body">
      <p>
        <p>Course Name: <%= @question_paper.name %></p>
        <p>Course Code: <%= @question_paper.code %></p>
        <p>Full Marks:  <%= @question_paper.fullmark %></p>
        <p>Paper difficulty: <%= @question_paper.paper_difficulty %></p>
        <p>Modules: <%= @question_paper.module %></p>
      </p>
    </section>
    <div class="confirmation">
      <%= link_to "Confirm", question_paper_path(@question_paper, format: "pdf"), target: "_blank", class: "btn btn-lg btn-success" %>
      <%= link_to "Back to Create Question", paper_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/question_papers/exam_paper.pdf.erb
<div class="row">
  <div class="col-md-12">
    <section class="paper_head">
      <h2>Daffodil International University</h2>
      <p>Course Name: <%= @question_paper.name %></p>
      <p>Course Code: <%= @question_paper.code %></p>
      <p>Full Marks:  <%= @question_paper.fullmark %></p>
    </section>

    <section class="paper_body">
      <% if @fullmark==25 %>
        <% if @module==2 %>
          <%= render 'pdf_formats/mod2_25' %>
        <% elsif @module==3 %>
          <%= render 'pdf_formats/mod3_25' %>
        <% elsif @module==4 %>
          <%= render 'pdf_formats/mod4_25' %>
        <% elsif @module==5 %>
          <%= render 'pdf_formats/mod5_25' %>
        <% end %>
      <% elsif @fullmark==40 %>
        <% if @module==3 %>
          <%= render 'pdf_formats/mod3_40' %>
        <% elsif @module==4 %>
          <%= render 'pdf_formats/mod4_40' %>
        <% elsif @module==5%>
          <%= render 'pdf_formats/mod5_40' %>
        <% end %>
      <% end %>

    </section>
  </div>
</div>

app/views/question_papers/new.html.erb
<% provide(:title, 'Create Question Paper') %>
<% provide(:button_text, 'Create') %>

<h1>Create Question Paper</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/question_papers/next.html.erb
<% provide(:title, 'Next Page') %>
<% provide(:button_text, 'Create') %>

<h1>Create Question Paper</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag(exam_paper_path, method: :get) do %>
      <%= label_tag :difficulty %>
      <%= select_tag "difficulty", raw("<option>easy</option><option>medium</option><option>hard</option>")  %>


      <%= label_tag :course %>
      <%= text_field_tag :course, params[:course] %>

      <%= submit_tag yield(:button_text), name: nil, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/question_papers/show.html.erb
<div class="row">
  <div class="col-md-12">
    <section class="paper_head">
      <h2>Daffodil International University</h2>
      <p>Course Name: <%= @question_paper.name %></p>
      <p>Course Code: <%= @question_paper.code %></p>
      <p>Full Marks:  <%= @question_paper.fullmark %></p>
    </section>

    <section class="paper_body">
      <% if @fullmark==25 %>
        <% if @module==2 %>
          <%= render 'paper_formats/mod2_25' %>
        <% elsif @module==3 %>
          <%= render 'paper_formats/mod3_25' %>
        <% elsif @module==4 %>
          <%= render 'paper_formats/mod4_25' %>
        <% elsif @module==5 %>
          <%= render 'paper_formats/mod5_25' %>
        <% end %>
      <% elsif @fullmark==40 %>
        <% if @module==3 %>
          <%= render 'paper_formats/mod3_40' %>
        <% elsif @module==4 %>
          <%= render 'paper_formats/mod4_40' %>
        <% elsif @module==5%>
          <%= render 'paper_formats/mod5_40' %>
        <% end %>
      <% end %>
    </section>

    <%= link_to "view PDF", question_paper_path(@question_paper, format: "pdf") %>
  </div>
</div>

app/views/question_papers/show.pdf.erb
<div class="row">
  <div class="col-md-12">
    <section class="paper_head">
      <h2>Daffodil International University</h2>
      <p>Course Name: <%= @question_paper.name %></p>
      <p>Course Code: <%= @question_paper.code %></p>
      <p>Full Marks:  <%= @question_paper.fullmark %></p>
    </section>

    <section class="paper_body">
      <% if @fullmark==25 %>
        <% if @module==2 %>
          <%= render 'pdf_formats/mod2_25' %>
        <% elsif @module==3 %>
          <%= render 'pdf_formats/mod3_25' %>
        <% elsif @module==4 %>
          <%= render 'pdf_formats/mod4_25' %>
        <% elsif @module==5 %>
          <%= render 'pdf_formats/mod5_25' %>
        <% end %>
      <% elsif @fullmark==40 %>
        <% if @module==3 %>
          <%= render 'pdf_formats/mod3_40' %>
        <% elsif @module==4 %>
          <%= render 'pdf_formats/mod4_40' %>
        <% elsif @module==5%>
          <%= render 'pdf_formats/mod5_40' %>
        <% end %>
      <% end %>

    </section>
  </div>
</div>